const stakingABI = [
  {
    "inputs":[{"internalType":"address","name":"_g3xToken","type":"address"}],
    "stateMutability":"nonpayable",
    "type":"constructor"
  },
  {
    "inputs":[{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"uint16","name":"duration","type":"uint16"}],
    "name":"stake","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[{"internalType":"uint256","name":"index","type":"uint256"}],
    "name":"claim","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[{"internalType":"uint256","name":"index","type":"uint256"}],
    "name":"unstake","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[{"internalType":"uint256","name":"amount","type":"uint256"}],
    "name":"depositRewards","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[{"internalType":"uint16","name":"duration","type":"uint16"},{"internalType":"uint16","name":"newApr","type":"uint16"}],
    "name":"setAPR","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[{"internalType":"address","name":"user","type":"address"}],
    "name":"getStakeCount","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],
    "stateMutability":"view","type":"function"
  }
];
